name: test_task_hp_houses
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  responsive_grid: ^2.4.4
  rxdart: ^0.27.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

